### ISSUE TITLE
App doesn't work on Galaxy Watch3

### ISSUE THREAD

**Issue by jgosar** [wansti/OwntracksOSM#1]
Device: Galaxy Watch3
Model number: SM-R840
One UI: 2.0
Tizen: 5.5.0.1
Software version: R840XXU1BTK1

App version: 1.0.1 (Downloaded from Galaxy Store)

Problem: When I open the app, all I see is this:
![image](https://user-images.githubusercontent.com/36840705/102963600-cbab4500-44e9-11eb-895f-0766aaa86561.png)

None of the buttons respond to any touch.

**Comment by KnallbertLp** [comment]
I have the same issue on my active 2 (bt) on the latest software release

**Comment by FTG1961** [comment]
I have the same issue on my  GW3 (LTE). Please Update

**Comment by FTG1961** [comment]
Change language in english. Works fine

**Comment by wansti** [comment]
I applied @jgosar's fix and submitted the update to the Galaxy Store. Will probably take a few days to show up. Happy Easter!
