### ISSUE TITLE
Galaxy Watch4 / WearOS

### ISSUE THREAD

**Issue by janstadt** [wansti/OwntracksOSM#7]
I currently have a galaxy watch 3 with this app running and its working alright. I just recently upgraded the phone to the WearOS version and was curious if anyone has any recommendations for an alternative app that will work with that? I cant seem to find a OwnTracks WearOS app that would do the equivalent so i figure i'd ask here?

**Comment by wansti** [comment]
There is a mapping app called LocusMap made by a small dedicated team in the Czech Republic. It doesn't support Owntracks directly but it's possible to make it record tracks to a custom server (e.g. Nextcloud, and there are also server side scripts available somewhere that connect it to Owntracks if I remember correctly). It has a live tracking feature and companion apps for Tizen and WearOS. It's a subscription based app (source code for the WearOS app is available on GitHub, and I've contributed some patches for the Galaxy Watch 4). I use this app quite a lot and eventually it replaced my Owntracks setup. 

On 2 February 2022 6:20:43 am AEDT, Jake Anstadt ***@***.***> wrote:
>I currently have a galaxy watch 3 with this app running and its working alright. I just recently upgraded the phone to the WearOS version and was curious if anyone has any recommendations for an alternative app that will work with that? I cant seem to find a OwnTracks WearOS app that would do the equivalent so i figure i'd ask here? 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/wansti/OwntracksOSM/issues/7
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by janstadt** [comment]
Thanks for the quick reply. I'll have to take a look at it. I have a HA instance set up with MQTT exposed and really am just looking to track my daughters location more than all the additional features within Locus. I am having a hard time finding a free MQTT client for WearOS that fits the bill but will keep looking. If you have any other suggestions that would be great!

**Comment by janstadt** [comment]
Cripes, i bet i can just install homeassistant on the wear os device and it'll keep track of location for me. hmmmmmmm. :-)

**Comment by wansti** [comment]
Hahaha :-)
For the kids I would just set up the SOS feature on the watches. Whenever they feel unsafe they can just press the home button three times and the watch will send their location to your phone for an hour. It won't track them continuously (or for as long as the battery lasts), instead they get to decide when they think it's appropriate. Personally I would prefer that both from a data security and an educational point of view. 

On 2 February 2022 8:00:27 am AEDT, Jake Anstadt ***@***.***> wrote:
>Cripes, i bet i can just install homeassistant on the wear os device and it'll keep track of location for me. hmmmmmmm. :-)
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/wansti/OwntracksOSM/issues/7#issuecomment-1027281329
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by janstadt** [comment]
Interesting. I might have to take a look at that. Thanks again for the reply!
